AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'Rakefile'
    - '*.gemspec'

AndOr:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  Enabled: false

